### ISSUE TITLE
Milestone 1: Feedback

### ISSUE THREAD

**Issue by thasus** [UBC-MDS/worldly-wines#10]
The description of the overview and app usage scenario were good. 
There was some confusion regarding what your 6th variable was - wine name or points level? Being more clear or definitive about this would have helped. 
Another concern is the lack of a price filter in the sketch despite a price range being referred to in the usage scenario. 
But overall good job!

**Comment by EvanYathon** [comment]
Hi, thanks for the feedback!  Looking forward to more for milestone 3.
