### ISSUE TITLE
Peer Review: Milestone 3

### ISSUE THREAD

**Issue by HarjyotKaur** [UBC-MDS/worldly-wines#14]
The app has clarity in terms deliverables. It encompasses apt amount of information without overwhelming the user. Following are some suggestion for improvements:

- Ordering the legend "quality" wise, so that it reads high, medium and then low

- A little clarity on what is "points". It is a little difficult for a user to guess it just by viewing the chart? Maybe it could termed as "rating", instead of "points".

- The country drop-down allows multiple selection of countries but a comparison metric is missing. Few ways to implement that could be:
   - Using a chlororopeth world map
   -  Given the size of dataset it could be less feasible adding latitudes and longitudes to the data. In that  case scenario, one way out could be giving user the flexibility of comparing only two countries at a time so that the existing charts are not over-populated
   - Or you could restrict the drop-down and allow the user to select only one country

- The province drop-down is not in sync with the country drop-down. 
  - The user might not prior knowledge of the provinces that belong to a country. You could adapt the province drop-down list based on the country selected
  - This would also help with the drop-down list being shorter 

-If no country or province is selected, there are two plots that show nothing but the  plot with price vs density shows an error, may be you could add a blank template for that too, like the others

- Currently, the main tab has three charts and the user has to scroll down to view the third chart, it can be shifted to another tab.

**Comment by EvanYathon** [comment]
Hi Shane and Harjyot, thanks for the feedback!

- Reordered the legend
- Names of plots and axis labels changed for clarity on points
- Changed country to only one dropdown item
- Synced province choices with country
- Added a second tab for the crossplot
