### ISSUE TITLE
Feedback Milestone 2

### ISSUE THREAD

**Issue by thasus** [UBC-MDS/worldly-wines#15]
Really good job! Neat, clean, well organized code, app deployed well. 

I see what you mean about the Country and Province filter issue. Is it possible to insert a row of dummy zeros and set that as a default "Please select option". That or you could provide a brief write-up targeted at Canadians to buy more Canadian wines!

Consider rearranging your quality filters to Low, Medium, High

**Comment by EvanYathon** [comment]
Thanks for the feedback!

- For the filter issue, we compromised by only allowing one selected country for cleanliness and usability [here](https://github.com/UBC-MDS/worldly-wines/commit/1e6d76b6077acb363a2134ad76611183afee6f85)
- Quality filters are reordered [here](https://github.com/UBC-MDS/worldly-wines/commit/3fea49f1bbcfb30557f2a7aad9de0197fccef228)
